# Generated by Django 3.1.2 on 2020-11-03 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, null=True)),
                ('slug', models.SlugField(max_length=40, null=True)),
                ('image', models.ImageField(blank=True, default='artist_picture/default.png', null=True, upload_to='artist_picture/', verbose_name='artist Picture')),
                ('description', models.TextField(max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video_Clip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, null=True)),
                ('video_Format', models.CharField(choices=[('m4v', 'M4V'), ('mp4', 'MP4')], default='M4V', max_length=40, null=True)),
                ('published', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, default='video_thumbnail/default.png', null=True, upload_to='video_thumbnail/', verbose_name='Video Thumbnail')),
                ('link', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(max_length=1000, null=True)),
                ('artist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.artist')),
                ('genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.genre')),
            ],
            options={
                'verbose_name': 'Video Clip',
            },
        ),
        migrations.CreateModel(
            name='Albume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, null=True)),
                ('slug', models.SlugField(max_length=40, null=True)),
                ('audio_Format', models.CharField(choices=[('m4a', 'M4A'), ('mp3', 'MP3'), ('flac', 'FLAC')], default='M4A', max_length=40, null=True)),
                ('published', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, default='albume_art/default.png', null=True, upload_to='albume_art/', verbose_name='Albume Art')),
                ('link', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(max_length=1000, null=True)),
                ('artist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.artist')),
                ('genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.genre')),
            ],
        ),
    ]
