# Generated by Django 3.1.2 on 2020-11-03 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20201103_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='slug',
            field=models.SlugField(max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='video_clip',
            name='slug',
            field=models.SlugField(max_length=40, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='albume',
            name='name',
            field=models.CharField(max_length=40, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='albume',
            name='slug',
            field=models.SlugField(max_length=40, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=40, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=40, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='video_clip',
            name='name',
            field=models.CharField(max_length=40, null=True, unique=True),
        ),
    ]
