# Generated by Django 3.1.2 on 2020-11-04 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20201104_0037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ['-id']},
        ),
    ]
