# Generated by Django 3.1.2 on 2020-11-05 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20201104_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video_clip',
            name='link',
            field=models.CharField(default='Copy link Here', max_length=100, null=True),
        ),
    ]
