# Generated by Django 3.1.2 on 2020-11-05 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20201105_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='video_clip',
            name='status',
            field=models.CharField(choices=[('active', 'ACTIVE'), ('inactive', 'INACTIVE')], default='ACTIVE', max_length=40, null=True),
        ),
    ]
