# Generated by Django 3.1.2 on 2020-12-04 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20201106_0340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albume',
            name='genre',
        ),
        migrations.AddField(
            model_name='albume',
            name='genre',
            field=models.ManyToManyField(to='myapp.Genre'),
        ),
    ]
