# Generated by Django 3.1.2 on 2020-12-04 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_auto_20201204_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albume',
            name='genre',
            field=models.ManyToManyField(related_name='Albume', to='myapp.Genre'),
        ),
    ]
