# Generated by Django 3.1.2 on 2020-12-04 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_auto_20201204_1951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albume',
            name='genre',
        ),
        migrations.AddField(
            model_name='albume',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.genre'),
        ),
    ]
